#!/usr/bin/env bash
#
# Type-check and lint Slipstream's Linux-gated Rust from any development machine.
#
#   scripts/xcheck.sh                    # clippy with warnings denied
#   scripts/xcheck.sh check              # cargo check
#   scripts/xcheck.sh clippy --fix       # extra args are passed through to cargo
#
# CI compiles Linux-gated code on Linux, so an edit made on another OS is otherwise unverifiable
# until that job runs. This script checks the working tree in a short-lived generated workspace.
#
# The generated workspace keeps the Linux display check independent of the full host dependency
# graph. ss-capture is excluded because its Linux path requires a system PipeWire development package.
# Path dependencies outside the generated members point at the real crates by absolute path, while
# the lightweight stubs keep unrelated multimedia and transport dependencies out of the check.
#
# ss-encode is stubbed because ss-vdisplay's admission gate needs only one predicate from it, while
# the real crate carries multimedia build dependencies. If the display path starts using another
# encoder fact, mirror that fact here.
#
# cargo fmt needs none of this. Rustfmt follows mod and path declarations without evaluating cfg.
set -euo pipefail

REPO="$(cd "$(dirname "$(readlink -f "$0")")/.." && pwd)"

# Accept the old explicit Linux argument while keeping the checker single-platform.
if [ "${1:-}" = linux ]; then
  shift
fi

TARGET=x86_64-unknown-linux-gnu
LINT=(ss-vdisplay)
OUT="${XCHECK_DIR:-$REPO/target/xcheck-linux}"

# The generated members: every crate we lint on EITHER target, plus the two stubs they share. A path
# dep naming one of these must stay RELATIVE (resolving to the generated member); anything else is
# rewritten to the real crate. Getting that backwards silently drags the real slipstream-core — and
# with it ring and opus — back in through ss-frame, which is the entire thing this avoids.
MEMBERS_RE='slipstream-core|ss-encode|ss-frame|ss-vdisplay'
REAL_MEMBERS=(ss-frame ss-vdisplay)

cmd="${1:-clippy}"
[ $# -gt 0 ] && shift
case "$cmd" in
  check | clippy) ;;
  *)
    echo "usage: $(basename "$0") [linux] [check|clippy] [extra cargo args...]" >&2
    exit 2
    ;;
esac

if ! rustc --print target-list | grep -qx "$TARGET"; then
  echo "xcheck: rustc does not know $TARGET" >&2
  exit 1
fi
if ! rustup target list --installed 2>/dev/null | grep -qx "$TARGET"; then
  echo "xcheck: target $TARGET not installed for the active toolchain — run:" >&2
  echo "    rustup target add $TARGET" >&2
  exit 1
fi

rm -rf "$OUT"
mkdir -p "$OUT"

# Mirror the real [workspace.package] so the members' `version.workspace = true` resolves.
{
  echo '# GENERATED by scripts/xcheck.sh — do not edit; re-run the script.'
  echo '[workspace]'
  echo 'resolver = "2"'
  echo 'members = ["slipstream-core", "ss-encode", "ss-frame", "ss-vdisplay"]'
  echo
  echo '[workspace.package]'
  sed -n '/^\[workspace\.package\]/,/^$/p' "$REPO/Cargo.toml" | sed '1d;/^$/d'
  # …and the real [workspace.lints.*] tables. Every crate manifest now carries
  # `[lints] workspace = true` (the workspace-wide unsafe discipline), and a member inheriting a
  # lint table the generated ROOT does not define does not merely lose the lint — cargo refuses to
  # parse the manifest at all ("error inheriting `lints` from workspace root manifest's
  # `workspace.lints`"), which broke this script outright the day that landed. Mirrored generically
  # so a new table (clippy, rustdoc, …) is picked up without touching this script again.
  echo
  awk '/^\[/ { in_lints = ($0 ~ /^\[workspace\.lints/) } in_lints' "$REPO/Cargo.toml"
} > "$OUT/Cargo.toml"

mkdir -p "$OUT/slipstream-core/src"
cat > "$OUT/slipstream-core/Cargo.toml" <<'EOF'
# GENERATED by scripts/xcheck.sh — a STUB, not the real crate.
[package]
name = "slipstream-core"
version.workspace = true
edition = "2021"
rust-version.workspace = true

[features]
default = []
# Present so dependents' `features = ["quic"]` resolves; carries no quinn/rustls/opus.
quic = []
EOF

# Field layout and derives must match the real definitions, or the cross-check goes stale exactly
# where it matters (the capture code builds HdrMeta literally and compares Modes).
cat > "$OUT/slipstream-core/src/lib.rs" <<'EOF'
//! GENERATED by scripts/xcheck.sh - a STUB of slipstream-core carrying only the types used by the
//! Linux display check. Mirrors crates/slipstream-core: `Mode` from config.rs, `HdrMeta` from
//! quic/datagram.rs, and `CompositorPref` from config.rs. If any grows a field, mirror it here.

/// Mirrors `slipstream_core::Mode`.
#[repr(C)]
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Mode {
    pub width: u32,
    pub height: u32,
    pub refresh_hz: u32,
}

/// Mirrors `slipstream_core::CompositorPref` (config.rs). ss-vdisplay matches on every variant and
/// calls `as_str`, so both the variant set and the strings must stay in step with the real enum.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
pub enum CompositorPref {
    #[default]
    Auto,
    Kwin,
    Wlroots,
    Mutter,
    Gamescope,
}

impl CompositorPref {
    pub fn as_str(self) -> &'static str {
        match self {
            CompositorPref::Auto => "auto",
            CompositorPref::Kwin => "kwin",
            CompositorPref::Wlroots => "wlroots",
            CompositorPref::Mutter => "mutter",
            CompositorPref::Gamescope => "gamescope",
        }
    }
}

pub mod quic {
    /// Mirrors `slipstream_core::quic::HdrMeta`.
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Default)]
    pub struct HdrMeta {
        pub display_primaries: [[u16; 2]; 3],
        pub white_point: [u16; 2],
        pub max_display_mastering_luminance: u32,
        pub min_display_mastering_luminance: u32,
        pub max_cll: u16,
        pub max_fall: u16,
    }
}
EOF

mkdir -p "$OUT/ss-encode/src"
cat > "$OUT/ss-encode/Cargo.toml" <<'EOF'
# GENERATED by scripts/xcheck.sh — a STUB, not the real crate.
[package]
name = "ss-encode"
version.workspace = true
edition = "2021"
rust-version.workspace = true
EOF

cat > "$OUT/ss-encode/src/lib.rs" <<'EOF'
//! GENERATED by scripts/xcheck.sh - a STUB of ss-encode carrying only the one item ss-vdisplay's
//! admission gate uses. The real crate carries multimedia build dependencies; the display path
//! needs only this predicate.

/// Mirrors `ss_encode::can_open_another_session` for the display check.
pub fn can_open_another_session() -> bool {
    true
}
EOF

for name in "${REAL_MEMBERS[@]}"; do
  mkdir -p "$OUT/$name"
  # Park the member paths behind a sentinel first: a plain self-substitution would be a no-op and
  # the next rule would rewrite them to absolute along with everything else.
  {
    echo "# GENERATED by scripts/xcheck.sh from crates/$name/Cargo.toml — contents are symlinks."
    sed -E "s#path = \"\.\./($MEMBERS_RE)\"#path = \"@@M@@\1\"#g; \
            s#path = \"\.\./([A-Za-z0-9_-]+)\"#path = \"$REPO/crates/\1\"#g; \
            s#path = \"@@M@@#path = \"../#g" "$REPO/crates/$name/Cargo.toml"
  } > "$OUT/$name/Cargo.toml"
  # Symlink EVERY entry, not just src/: ss-vdisplay's `wayland_scanner::generate_interfaces!` reads
  # `protocols/*.xml` relative to CARGO_MANIFEST_DIR, which is this generated member. Without the
  # protocols dir the proc macro panics and every generated Wayland type resolves to nothing — ~20
  # cascading errors that look like a code problem and are not.
  for entry in "$REPO/crates/$name"/*; do
    case "$(basename "$entry")" in
      Cargo.toml | target) continue ;;
    esac
    ln -sfn "$entry" "$OUT/$name/$(basename "$entry")"
  done
done

cd "$OUT"
for name in "${LINT[@]}"; do
  echo "=== $cmd $name ($TARGET) ==="
  if [ "$cmd" = clippy ]; then
    cargo clippy --target "$TARGET" -p "$name" --all-targets "$@" -- -D warnings
  else
    cargo check --target "$TARGET" -p "$name" --all-targets "$@"
  fi
done
